//! Build-time data pipeline.
//!
//! Reads the human-editable word lists in `data/` and compiles them into
//! `OUT_DIR/tables.rs`:
//!   * sorted, deduplicated word arrays for fast dictionary lookup,
//!   * parallel frequency-rank arrays (rank 0 = most frequent) used by the
//!     autocomplete engine to pick the best completion, and
//!   * per-language character bigram log-probability matrices (Laplace-smoothed)
//!     used by the wrong-layout detector.
//!
//! Keeping this at build time means the binary embeds compact static tables
//! (a few hundred KB) with no startup parsing cost.

use std::collections::HashSet;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

const EN_ALPHABET: &str = "abcdefghijklmnopqrstuvwxyz";
const RU_ALPHABET: &str = "абвгдеёжзийклмнопрстуфхцчшщъыьэюя";

/// Cap dictionary sizes to keep the binary small.
const EN_MAX: usize = 45_000;
const RU_MAX: usize = 50_000;

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let data = manifest.join("..").join("..").join("data");
    // English: a large frequency list, a clean common-word list, and curated
    // IT/CLI terms that frequency lists miss.
    let en_freq = data.join("en_50k.txt");
    let en_common = data.join("google-10000-english.txt");
    let it_terms = data.join("it_terms.txt");
    let ru_path = data.join("ru_50k.txt");

    for p in [&en_freq, &en_common, &it_terms, &ru_path] {
        println!("cargo:rerun-if-changed={}", p.display());
    }

    // Words in frequency order (position = rank, 0 = most frequent).
    let mut en_words = load_freq(&en_freq, EN_ALPHABET, EN_MAX);
    merge_plain(&mut en_words, &en_common, EN_ALPHABET);
    merge_plain(&mut en_words, &it_terms, EN_ALPHABET);
    let ru_words = load_freq(&ru_path, RU_ALPHABET, RU_MAX);

    // Alphabetical order for binary search, with a parallel rank array.
    let (en_words, en_ranks) = sorted_with_ranks(en_words);
    let (ru_words, ru_ranks) = sorted_with_ranks(ru_words);

    let en_bigram = bigram_table(&en_words, EN_ALPHABET);
    let ru_bigram = bigram_table(&ru_words, RU_ALPHABET);

    let mut out = String::new();
    out.push_str("// @generated by build.rs — do not edit.\n");
    writeln!(out, "pub const EN_ALPHABET: &str = {:?};", EN_ALPHABET).unwrap();
    writeln!(out, "pub const RU_ALPHABET: &str = {:?};", RU_ALPHABET).unwrap();
    emit_words(&mut out, "EN_WORDS", &en_words);
    emit_words(&mut out, "RU_WORDS", &ru_words);
    emit_ranks(&mut out, "EN_RANKS", &en_ranks);
    emit_ranks(&mut out, "RU_RANKS", &ru_ranks);
    emit_matrix(
        &mut out,
        "EN_BIGRAM",
        &en_bigram,
        EN_ALPHABET.chars().count() + 1,
    );
    emit_matrix(
        &mut out,
        "RU_BIGRAM",
        &ru_bigram,
        RU_ALPHABET.chars().count() + 1,
    );

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    fs::write(out_dir.join("tables.rs"), out).unwrap();
}

/// Load a "word frequency" file (`word count` per line, most-frequent first),
/// keeping up to `max` words that are pure letters of `alphabet`.
/// File order is preserved so a word's index is its frequency rank.
fn load_freq(path: &PathBuf, alphabet: &str, max: usize) -> Vec<String> {
    let text = fs::read_to_string(path).unwrap_or_default();
    let mut seen = HashSet::new();
    let mut words = Vec::new();
    for line in text.lines() {
        if words.len() >= max {
            break;
        }
        let word = line.split_whitespace().next().unwrap_or("").to_lowercase();
        if !word.is_empty()
            && word.chars().all(|c| alphabet.contains(c))
            && seen.insert(word.clone())
        {
            words.push(word);
        }
    }
    words
}

/// Merge a plain one-word-per-line list into `words` (all new entries kept,
/// appended after the frequency list so they rank below it).
fn merge_plain(words: &mut Vec<String>, path: &PathBuf, alphabet: &str) {
    let mut seen: HashSet<String> = words.iter().cloned().collect();
    let text = fs::read_to_string(path).unwrap_or_default();
    for line in text.lines() {
        let w = line.trim().to_lowercase();
        if !w.is_empty() && w.chars().all(|c| alphabet.contains(c)) && seen.insert(w.clone()) {
            words.push(w);
        }
    }
}

/// Sort frequency-ordered `words` alphabetically, returning the sorted list
/// plus a parallel array of each word's original frequency rank.
fn sorted_with_ranks(words: Vec<String>) -> (Vec<String>, Vec<u16>) {
    assert!(
        words.len() < u16::MAX as usize,
        "word count exceeds u16 rank range"
    );
    let mut pairs: Vec<(String, u16)> = words
        .into_iter()
        .enumerate()
        .map(|(i, w)| (w, i as u16))
        .collect();
    pairs.sort_unstable_by(|a, b| a.0.cmp(&b.0));
    pairs.into_iter().unzip()
}

/// Build a Laplace-smoothed bigram log-probability matrix over
/// `alphabet` + one boundary symbol (index = alphabet length).
///
/// Rows are the "from" symbol, columns the "to" symbol. Each word contributes
/// the transitions `^ w0`, `w0 w1`, …, `wn $`.
fn bigram_table(words: &[String], alphabet: &str) -> Vec<Vec<f32>> {
    let idx: std::collections::HashMap<char, usize> =
        alphabet.chars().enumerate().map(|(i, c)| (c, i)).collect();
    let n = alphabet.chars().count();
    let boundary = n; // extra symbol
    let size = n + 1;

    let mut counts = vec![vec![0u64; size]; size];
    for w in words {
        let mut prev = boundary;
        for c in w.chars() {
            let Some(&cur) = idx.get(&c) else { continue };
            counts[prev][cur] += 1;
            prev = cur;
        }
        counts[prev][boundary] += 1; // transition into end-of-word
    }

    // Laplace add-1 smoothing -> natural-log probabilities.
    let mut logp = vec![vec![0f32; size]; size];
    for i in 0..size {
        let total: u64 = counts[i].iter().sum();
        let denom = (total + size as u64) as f64;
        for j in 0..size {
            let p = (counts[i][j] as f64 + 1.0) / denom;
            logp[i][j] = p.ln() as f32;
        }
    }
    logp
}

fn emit_words(out: &mut String, name: &str, words: &[String]) {
    writeln!(out, "pub static {name}: &[&str] = &[").unwrap();
    for w in words {
        writeln!(out, "    {w:?},").unwrap();
    }
    out.push_str("];\n");
}

fn emit_ranks(out: &mut String, name: &str, ranks: &[u16]) {
    writeln!(out, "pub static {name}: &[u16] = &[").unwrap();
    for chunk in ranks.chunks(20) {
        out.push_str("    ");
        for r in chunk {
            write!(out, "{r},").unwrap();
        }
        out.push('\n');
    }
    out.push_str("];\n");
}

fn emit_matrix(out: &mut String, name: &str, m: &[Vec<f32>], size: usize) {
    writeln!(out, "pub static {name}: [[f32; {size}]; {size}] = [").unwrap();
    for row in m {
        out.push_str("    [");
        for v in row {
            write!(out, "{v:.4}f32,").unwrap();
        }
        out.push_str("],\n");
    }
    out.push_str("];\n");
}
