//! Build-time data pipeline.
//!
//! Reads the human-editable word lists in `data/` and compiles them into
//! `OUT_DIR/tables.rs`:
//!   * sorted, deduplicated word arrays for fast dictionary lookup, and
//!   * per-language character bigram log-probability matrices (Laplace-smoothed)
//!     used by the wrong-layout detector.
//!
//! Keeping this at build time means the binary embeds compact static tables
//! (a few hundred KB) with no startup parsing cost.

use std::collections::BTreeSet;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

const EN_ALPHABET: &str = "abcdefghijklmnopqrstuvwxyz";
const RU_ALPHABET: &str = "абвгдеёжзийклмнопрстуфхцчшщъыьэюя";

/// Cap dictionary sizes to keep the binary small.
const EN_MAX: usize = 45_000;
const RU_MAX: usize = 50_000;

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let data = manifest.join("..").join("..").join("data");
    // English: a large frequency list, a clean common-word list, and curated
    // IT/CLI terms that frequency lists miss.
    let en_freq = data.join("en_50k.txt");
    let en_common = data.join("google-10000-english.txt");
    let it_terms = data.join("it_terms.txt");
    let ru_path = data.join("ru_50k.txt");

    for p in [&en_freq, &en_common, &it_terms, &ru_path] {
        println!("cargo:rerun-if-changed={}", p.display());
    }

    let mut en_words = load_freq(&en_freq, EN_ALPHABET, EN_MAX);
    merge_plain(&mut en_words, &en_common, EN_ALPHABET);
    merge_plain(&mut en_words, &it_terms, EN_ALPHABET);
    let en_words: Vec<String> = en_words.into_iter().collect();
    let ru_words = load_freq(&ru_path, RU_ALPHABET, RU_MAX)
        .into_iter()
        .collect::<Vec<_>>();

    let en_bigram = bigram_table(&en_words, EN_ALPHABET);
    let ru_bigram = bigram_table(&ru_words, RU_ALPHABET);

    let mut out = String::new();
    out.push_str("// @generated by build.rs — do not edit.\n");
    writeln!(out, "pub const EN_ALPHABET: &str = {:?};", EN_ALPHABET).unwrap();
    writeln!(out, "pub const RU_ALPHABET: &str = {:?};", RU_ALPHABET).unwrap();
    emit_words(&mut out, "EN_WORDS", &en_words);
    emit_words(&mut out, "RU_WORDS", &ru_words);
    emit_matrix(
        &mut out,
        "EN_BIGRAM",
        &en_bigram,
        EN_ALPHABET.chars().count() + 1,
    );
    emit_matrix(
        &mut out,
        "RU_BIGRAM",
        &ru_bigram,
        RU_ALPHABET.chars().count() + 1,
    );

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    fs::write(out_dir.join("tables.rs"), out).unwrap();
}

/// Load a "word frequency" file (`word count` per line, most-frequent first),
/// keeping up to `max` words that are pure letters of `alphabet`.
fn load_freq(path: &PathBuf, alphabet: &str, max: usize) -> BTreeSet<String> {
    let text = fs::read_to_string(path).unwrap_or_default();
    let mut set = BTreeSet::new();
    let mut taken = 0usize;
    for line in text.lines() {
        if taken >= max {
            break;
        }
        let word = line.split_whitespace().next().unwrap_or("").to_lowercase();
        if !word.is_empty() && word.chars().all(|c| alphabet.contains(c)) && set.insert(word) {
            taken += 1;
        }
    }
    set
}

/// Merge a plain one-word-per-line list into `set` (all entries kept).
fn merge_plain(set: &mut BTreeSet<String>, path: &PathBuf, alphabet: &str) {
    let text = fs::read_to_string(path).unwrap_or_default();
    for line in text.lines() {
        let w = line.trim().to_lowercase();
        if !w.is_empty() && w.chars().all(|c| alphabet.contains(c)) {
            set.insert(w);
        }
    }
}

/// Build a Laplace-smoothed bigram log-probability matrix over
/// `alphabet` + one boundary symbol (index = alphabet length).
///
/// Rows are the "from" symbol, columns the "to" symbol. Each word contributes
/// the transitions `^ w0`, `w0 w1`, …, `wn $`.
fn bigram_table(words: &[String], alphabet: &str) -> Vec<Vec<f32>> {
    let idx: std::collections::HashMap<char, usize> =
        alphabet.chars().enumerate().map(|(i, c)| (c, i)).collect();
    let n = alphabet.chars().count();
    let boundary = n; // extra symbol
    let size = n + 1;

    let mut counts = vec![vec![0u64; size]; size];
    for w in words {
        let mut prev = boundary;
        for c in w.chars() {
            let Some(&cur) = idx.get(&c) else { continue };
            counts[prev][cur] += 1;
            prev = cur;
        }
        counts[prev][boundary] += 1; // transition into end-of-word
    }

    // Laplace add-1 smoothing -> natural-log probabilities.
    let mut logp = vec![vec![0f32; size]; size];
    for i in 0..size {
        let total: u64 = counts[i].iter().sum();
        let denom = (total + size as u64) as f64;
        for j in 0..size {
            let p = (counts[i][j] as f64 + 1.0) / denom;
            logp[i][j] = p.ln() as f32;
        }
    }
    logp
}

fn emit_words(out: &mut String, name: &str, words: &[String]) {
    writeln!(out, "pub static {name}: &[&str] = &[").unwrap();
    for w in words {
        writeln!(out, "    {w:?},").unwrap();
    }
    out.push_str("];\n");
}

fn emit_matrix(out: &mut String, name: &str, m: &[Vec<f32>], size: usize) {
    writeln!(out, "pub static {name}: [[f32; {size}]; {size}] = [").unwrap();
    for row in m {
        out.push_str("    [");
        for v in row {
            write!(out, "{v:.4}f32,").unwrap();
        }
        out.push_str("],\n");
    }
    out.push_str("];\n");
}
